In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [25]:
data = pd.read_csv(r'C:\Users\Lenovo\Documents\Ironhack\DATA\movie_metadata.csv')
data.shape
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 2. Use crosstabs to show the number of moovies per country

In [26]:
pd.crosstab(data['country'], data['genres'].count())

col_0                 5043
country
Afghanistan              1
Argentina                4
Aruba                    1
Australia               55
Bahamas                  1
...                    ...
Turkey                   1
UK                     448
USA                   3807
United Arab Emirates     1
West Germany             3

[65 rows x 1 columns]

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [27]:
pd.crosstab( data['country'], [data['director_name'], data['genres']])

director_name                                 A. Raven Cruz  \
genres               Action|Adventure|Comedy|Fantasy|Sci-Fi
country
Afghanistan                                               0
Argentina                                                 0
Aruba                                                     0
Australia                                                 0
Bahamas                                                   0
...                                                     ...
Turkey                                                    0
UK                                                        0
USA                                                       1
United Arab Emirates                                      0
West Germany                                              0

director_name                                  Aaron Hann Aaron Schneider  \
genres               Drama|Horror|Mystery|Sci-Fi|Thriller   Drama|Mystery
country
Afghanistan                                             0               0
Argentina                                               0               0
Aruba                                                   0               0
Australia                                               0               0
Bahamas                                                 0               0
...                                                   ...             ...
Turkey                                                  0               0
UK                                                      0               0
USA                                                     1               1
United Arab Emirates                                    0               0
West Germany                                            0               0

director_name         Aaron Seltzer Abel Ferrara          Adam Brooks  \
genres               Comedy|Romance  Crime|Drama Comedy|Drama|Romance
country
Afghanistan                       0            0                    0
Argentina                         0            0                    0
Aruba                             0            0                    0
Australia                         0            0                    0
Bahamas                           0            0                    0
...                             ...          ...                  ...
Turkey                            0            0                    0
UK                                0            0                    0
USA                               1            1                    0
United Arab Emirates              0            0                    0
West Germany                      0            0                    0

director_name        Adam Carolla Adam Goldberg    Adam Green  \
genres                     Comedy Drama|Mystery Comedy|Horror
country
Afghanistan                     0             0             0
Argentina                       0             0             0
Aruba                           0             0             0
Australia                       0             0             0
Bahamas                         0             0             0
...                           ...           ...           ...
Turkey                          0             0             0
UK                              0             0             0
USA                             1             1             1
United Arab Emirates            0             0             0
West Germany                    0             0             0

director_name        Adam Jay Epstein  ... Zack Ward Zackary Adler  \
genres                         Comedy  ...    Horror   Crime|Drama
country                                ...
Afghanistan                         0  ...         0             0
Argentina                           0  ...         0             0
Aruba                               0  ...         0             0
Australia                           0  ...         0             0
Bahamas                             0  ...         0             0
...                               ...  ...       ...           ...
Turkey                              0  ...         0             0
UK                                  0  ...         0             1
USA                                 1  ...         1             0
United Arab Emirates                0  ...         0             0
West Germany                        0  ...         0             0

director_name                       Zak Penn                Zal Batmanglij  \
genres               Adventure|Comedy|Horror Drama|Mystery|Sci-Fi|Thriller
country
Afghanistan                                0                             0
Argentina                                  0                             0
Aruba                                      0                             0
Australia                                  0                             0
Bahamas                                    0                             0
...                                      ...                           ...
Turkey                                     0                             0
UK                                         1                             0
USA                                        0                             1
United Arab Emirates                       0                             0
West Germany                               0                             0

director_name                              Zoran Lisinac  \
genres               Drama|Thriller Comedy|Music|Romance
country
Afghanistan                       0                    0
Argentina                         0                    0
Aruba                             0                    0
Australia                         0                    0
Bahamas                           0                    0
...                             ...                  ...
Turkey                            0                    0
UK                                1                    0
USA                               0                    1
United Arab Emirates              0                    0
West Germany                      0                    0

director_name            Álex de la Iglesia Émile Gaudreault  \
genres               Crime|Mystery|Thriller     Comedy|Drama
country
Afghanistan                               0                0
Argentina                                 0                0
Aruba                                     0                0
Australia                                 0                0
Bahamas                                   0                0
...                                     ...              ...
Turkey                                    0                0
UK                                        0                0
USA                                       0                0
United Arab Emirates                      0                0
West Germany                              0                0

director_name                        Éric Tessier         Étienne Faure
genres               Action|Drama|Horror|Thriller Drama|Musical|Romance
country
Afghanistan                                     0                     0
Argentina                                       0                     0
Aruba                                           0                     0
Australia                                       0                     0
Bahamas                                         0                     0
...                                           ...                   ...
Turkey                                          0                     0
UK                                              0                     0
USA                                             0                     0
United Arab Emirates                            0                     0
West Germany                                    0                     0

[65 rows x 4461 columns]

### 4. Average duration of filmes grouped by color

In [39]:
data['duration'].groupby(data['color']).mean()

color
 Black and White    112.253589
Color               107.042908
Name: duration, dtype: float64

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [40]:
data['movie_facebook_likes'].groupby(data['director_name']).mean()

director_name
A. Raven Cruz         128.0
Aaron Hann              0.0
Aaron Schneider         0.0
Aaron Seltzer         806.0
Abel Ferrara          344.0
                      ...
Zoran Lisinac         231.0
Álex de la Iglesia      0.0
Émile Gaudreault      352.0
Éric Tessier           39.0
Étienne Faure         114.0
Name: movie_facebook_likes, Length: 2398, dtype: float64

In [ ]:

pd.crosstab( data['director_name'], data['movie_facebook_likes'], aggfunc=np.average)